### ISSUE TITLE
feat: create front-end style guide to assist with Form API development

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/givewp#1570]
## User Story

As a developer, I want a front-end style guide so that I can extend Give in a manner consistent with the styles present in Give core.

## Current Behavior

I currently have to inspect the source code of a Give donation form using dev tools in order to see the markup and CSS classes used.

## Expected Behavior

I expect to have a style guide broken down by field so that I can quickly see the code and styles used to create each field. In doing so, I can extend Give more seamlessly.

This style guide would provide a reference from which to pull markup and classes when building out the Give Form API. It would also function as documentation going forward both internally and for other developers.

## Possible Solution

The front-end style guide should be built with hard-coded HTML/CSS/JS. Think of this style guide as a "super form" that includes an example of every type of field that is possible with Give. As such, the style guide should include:

- One Example of Each Field Type
	- Text
	- Textarea
	- Dropdown
	- Date
	- Radio
	- Checkbox
	- Email
	- Phone
	- File Upload
	- URL
	- Multi Select
	- Repeat Field
	- HTML
	- Section
- Goal
- Multi-level Donations
	- Buttons w/ custom amount
	- Radios  w/ custom amount
	- Dropdown  w/ custom amount
- Recurring Example
- Payment Method
- Personal Info
- Credit Card Info
- Billing Details
- Terms & Conditions
- Floating Labels Example

## Related

- http://semantic-ui.com/collections/form.html
- https://refills.bourbon.io/

## Tasks

- [ ] Create a mockup and agree upon Give default styles.
- [ ] Research and define form markup according to a11y best practices.
- [ ] Decide upon a grid system to lay out multi-column form fields.
- [ ] Style examples with Give default styling.

**Comment by DevinWalker** [comment]
Closing - out of date and we're working on a similar approach in Campaigns with Storybook + Tailwind and a bunch of other goodness.
