### ISSUE TITLE
epic: create a reactive table based layout for data listing pages

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#2925]
## User Story

As a `user`, I want `listings` like Donors and Donations to be built in an intuitive way so that `refreshing` doesn't require a page reload, I can then `export` based on the screen displayed and additional features. 

## Questions / Tasks

_To be determined and broken down into issues._

- [ ] Determine best table plugin for our needs (React based, shows images, exporting to CSV/Excel)
- [ ] Which WP REST API endpoints can we use or create to display necessary data?
- [ ] How can add-ons that add columns be compatible?

## Related
- https://github.com/WP-API/new-list-tables
- https://demos.telerik.com/kendo-ui/grid/editing
- https://datatables.net/
- https://reactabular.js.org/

... lots more to come. this is a placeholder.

**Comment by mathetos** [comment]
This looks really promising: 
* Project: https://github.com/bvaughn/react-virtualized
* Live Demo: https://bvaughn.github.io/react-virtualized/#/components/List

**Comment by DevinWalker** [comment]
Closing as we've created a Canny Feedback for this: https://givewp.canny.io/feature-requests/p/improve-data-listing-pages-like-donors-and-donations
