### ISSUE TITLE
feat: collect Donor mailing address mapped to Donor meta

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#3313]
## User Story

As a `Give Admin`, I want to be able to collect the donor's mailing address during donation and have that address populated in the Donor Details screen (donor meta, instead of donation meta).

Naturally, we already have the option to collect the Billing information, and while it is traditional to ask for Personal and then Billing, it seems more important to make Billing primary (mapped to donation/payment meta) since that often helps with fraud protection (in the case of Stripe and other gateways), then have a checkbox to indicate whether their Physical address is the same as the Billing or not, and if not, show the Physical address fields next. Something like this:

![image](https://user-images.githubusercontent.com/930724/40867163-116bd02e-65b7-11e8-9b12-9b5fa3f676c9.png)

## Current Behavior

I currently struggle with donor addresses because I'm collecting them at donation, but when I export my donations, the address does not appear at all. That seems to be because the address collected at donation is mapped to the donation meta and not the DONOR meta.

## Expected Behavior
With all of that in mind, I expect several things to happen:

- [ ] To be able to ask donors for their mailing address in addition to the billing address without having them duplicate effort if those two are the same.
- [ ] When I go to export donors, I want a setting to be able to export the billing address(es) associated with that donor in addition to the physical address collected at donation.
- [ ] At the Donor Detail screen, I expect to see both the Billing Address(es) collected during donation, as well as the Physical Address.
- [ ] I expect that if the same donor donates again with a different mailing address, that that will ALSO be added to the Donor Detail screen and I'll be able to choose which address should be treated as Primary and optionally be able to delete one or the other.

## Visuals

![image](https://user-images.githubusercontent.com/930724/40867244-a9a14022-65b7-11e8-88ba-03336ac0ee9d.png)

## Related

- https://github.com/WordImpress/Give/issues/3290
- HS Related issue: https://secure.helpscout.net/conversation/589621910/19167/?folderId=672197
- Many users have reported this over the years and it's caused confusion regularly. Searching HelScout for the "export" tag or "export address donor" gets lots of results that are relevant.

## Tasks

- [ ] Ensure all the items in the "Expected Behavior" section above work.
- [ ] Ensure that collecting this information is NOT sent to the payment gateways or interferes with payment gateway behavior in any way.
- [ ] Ensure that all exports that have donor information have the option to add the physical address

**Comment by kevinwhoffman** [comment]
> I currently struggle with donor addresses because I'm collecting them at donation, but when I export my donations, the address does not appear at all. That seems to be because the address collected at donation is mapped to the donation meta and not the DONOR meta.

You're correct that billing address does not appear in the `Export Donors` CSV under any circumstances, however sometimes billing address **IS** saved as donor meta. I'm experiencing two different behaviors based on offline vs. credit card donations.

## Offline Donation w/ Billing Details Enabled

- Billing address **IS** saved as donation meta in the `wp_give_paymentmeta` table.
- Billing address **IS NOT** saved as donor meta in the `wp_give_donormeta` table.
- Billing address **DOES NOT** appear in donor profile.

## Credit Card (Stripe) Donation

- Billing address **IS** saved as donation meta in the `wp_give_paymentmeta` table.
- Billing address **IS** saved as donor meta in the `wp_give_donormeta` table.
- Billing address **DOES** appear in donor profile.
- If I make a second donation with the same email and different billing address, then the billing address in donor meta is replaced.

## Suggestions

- Offline donation billing addresses should be saved as donor meta and appear within donor profile just like CC billing addresses.
- Mailing address details should be stored under their own meta keys in `wp_give_donormeta`.
- Mailing addresses and billing addresses should be distinguishable in Donor Profile.
- Under `Tools > Export > Export Donors`, we need to figure out how to handle exporting mailing and billing addresses if there are more than one of each.

**Comment by Benunc** [comment]
Weighing in here. Not just Billing address, but things like phone number and any other custom fields also need (the option to) to be mapped to the Donor Meta. There should be an option when creating a custom field (via Form Field Manager or otherwise) to map the data to one or both places. 

Here's a user story to illustrate:

I have an event for my nonprofit. On the form, I need to collect the following information:
- tshirt size *
- spouse/partner name *
- spouse t-shirt size *
- arrival time
- number of people attending
- phone number *
- mailing address **

Starred items need to be saved to both donation meta and donor meta, since I want to reuse that data. Non-starred items only need to be attached to the donation meta, because I won't need that information after this event. Double-starred items I really don't need on the donation meta, as I am going to only use that after the event to stay in touch.

I want the option to save to both places, or just one.

**Comment by mathetos** [comment]
I echo @Benunc strongly. The intent of this issue isn't simply for the Billing Address field, but to add logic generally that allows different fields to be mapped to donor meta and conditionally updated, whether those fields come from Give Core, Addons like Form Field Manager, or custom fields that have been coded by a developer.

**Comment by kevinwhoffman** [comment]
## Narrow Focus

While I understand the need for all of this, the mailing address issue at the top of the thread feels like something we can solve now, while a broader solution for associating individual fields with donors versus donations feels like a much larger issue for the Form API.

## One Source of Truth

I also feel it's very important to not establish two sources of truth for any form data. While a custom field may be valuable in both the Donor Profile and Donation details screen, that doesn't mean we have to store it in two different places (where it could get out of sync).

## Donation Snapshots

At the same time we want to maintain the integrity of each individual donation and create an accurate historical record of the exact data entered at the time of donation. If we store some fields as donor meta and those fields change, that should not affect the historical record of the donation.

One possibility is to store all fields in a serialized array as a snapshot for historical purposes. That array gets saved as post meta so that an accurate record can be pulled even if the mailing address has been updated since the donation. (Think about Amazon and how you can pull a receipt from any order in the past and trust that what you see was accurate at the date of purchase).

**Comment by mathetos** [comment]
1) I agree that we can get the easy win on this issue and wait for the Form API to resolve the bigger questions.
2) As far as "source of truth" I imagine that fields that update or add donor meta would add that info in both places, donation_meta and donor_meta. There's no avoiding the fact that we have donors and donations and they have two different purposes and each should get appropriate attention. Donation meta has not yet had the attention that it needs/deserves IMO.
3) Having the donor meta be added additionally from the donation solves your donation snapshot concern as well. When/if donor profile data is updated either via the profile editor, or wp-admin is would NOT affect the donation meta in any way, only donor meta.

But most of this discussion should be carried over to the relevant donation_meta issue under a Forms API epic.

**Comment by kevinwhoffman** [comment]
@Sidsector9 Let's keep this issue focused on the mailing address feature described in the original comment. Please create a plan and discuss with @ravinderk so that we have are sure to save the mailing address in the most appropriate location.

**Comment by DevinWalker** [comment]
I think we can move this issue forward without having to wait for the Form API development. We just have to ensure that the new API address field will have support for both the billing and personal address functionality we build in.

**Comment by stephaniehellwig** [comment]
Mailing address feature requested again:  https://secure.helpscout.net/conversation/881660352/41953?folderId=2805787

**Comment by JasonTheAdams** [comment]
**Triage:**
Closing this in favor of feedback gathered on Canny.
