### ISSUE TITLE
epic: add Stats API

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#3917]
# Feature Request

## User Story
As an admin, I want well developed Stats API, which helps me to extract complex Stats.

## Possible Solution
Update Stat API

## Related
https://github.com/impress-org/give/issues/3195

## Acceptance Criteria
- [x] Add Carbon PHP library to play with date easily (**if need**): https://carbon.nesbot.com/.
     
Update Stat API to get stat as mention below:
- [x] Donation Stat.
   - [x] Time Based
  -  [x] Growth Based ( for example: how much more or less donation we got in comparison of current and last week )
  - [ ] Category based
  - [ ] Tag Based
- [x] Donor Stat.
   - [x] Time Based
  -  [x] Growth Based
  - [ ] Category based
  - [ ] Tag Based
- [x] Form Stat.
   - [x] Time Based
  -  [x] Growth Based
  - [ ] Category based
  - [ ] Tag Based
- [x] Integration with Give Rest API
- [x] Integration with  Dashboard sales widget 

Additional
- [x] Backward compatibility: old Stat API code must work fine with updated.
- [x] Cache query if necessary
- [x] Test with addons
  - [x] Recurring
  - [x] Fee recovery
  - [x] Currency switcher
  - [x] Email Report

Future proposal:
- [ ] Integration with report page

**Comment by kevinwhoffman** [comment]
@ravinderk Devin and I have discussed and think we should freeze development of the Stats API until we have a better understanding of the data architecture and the reporting needs.

**Comment by DevinWalker** [comment]
Closing this older epic until we revisit stats.
