### ISSUE TITLE
Epic: Plugin Onboarding

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/givewp#4907]
## Pitch

The problem, solution, and constraints are defined within this document:  
[Pitch Document](https://docs.google.com/document/d/14SWr1gOJ0P99iymMKMCgzi8fLMe--IdXTNjUJjFAqK0/edit?usp=sharing)

> The **evaluating implementer** is the user best served by a guided onboarding process. This new user has some fundraising requirements in mind but is not tech-savvy, so they must be convinced that GiveWP is an improvement over their status quo.

## Appetite

6 Weeks

## Solution

- Welcome Wizard - most relevant to first-time new users; builds confidence and allows them to measure GiveWP’s capabilities against their requirements
- Setup Page - relevant to all fresh installs; ensures the required steps necessary to accept live donations are completed regardless of whether the user completed a wizard

## Definition of Done

> This project is done when a new user is able to complete the onboarding process and confirm with confidence whether GiveWP can meet their fundraising requirements. At a minimum, this process must allow the user to:

- [x] Share information about their cause
- [x] Set their location and currency
- [x] Define their fundraising requirements
- [x] Test their first donation form
- [x] Connect to a payment gateway (and configure webhook if necessary)

## Resources

- [Pitch Document](https://docs.google.com/document/d/14SWr1gOJ0P99iymMKMCgzi8fLMe--IdXTNjUJjFAqK0/)
- [Work Planning Document](https://docs.google.com/document/d/1OWa2nTrZlfNDNQwXdI5RuiIQXerCn3WT_7wItnvz30g/)
- [New User Experience](https://whimsical.com/BFG4LNa93LLunmNzzJGY6N)
- [Feature Dependency Tree](https://whimsical.com/G2stqkaeZiWXMphEpivquK)

**Comment by henryholtgeerts** [comment]
**Call Summary: Epic Breakdown 7/8/20**
_On Call: Kevin, Kyle, Henry_
Reviewed/discussed philosophy around Epics, and breaking them into issues
Reviewed simple dependency tree Kevin created for onboarding project
Discussed relationship between setup page and current welcome screen (determined setup screen will not directly replace welcome sreen)
Kyle and Henry discussed next steps (decided Kyle will work on Setup screen scaffolding, Henry will work on opening Wizard scaffolding issues)

Link to Kevin's simple onboarding project dependency tree: https://whimsical.com/G2stqkaeZiWXMphEpivquK

**Comment by kevinwhoffman** [comment]
## Call Summary
Participants: @kevinwhoffman @DevinWalker @kirklandharrell @mathetos 
Topic: Plugin Onboarding design handoff

### Result

Devin and Kirkland are going to meet today/tomorrow to kick off design based on the sketches. I've asked them to prioritize the design of the Setup Page before the Wizard.

### Next Steps

@kjohnson @henryholtgeerts Since you guys are leading this epic, it will be your responsibility to communicate design needs to Devin and Kirkland and manage those issues through the ZenHub pipeline.

Here's an example of a GitHub issue that would start in the `Design` pipeline and then move onto `Programming`.

- Issue title: Setup page design should be implemented
- Assignees: Henry, Devin, Kirkland
- Labels: `type: new feature`, `needs: design`
- Estimate: `4` (1 day for design, 2 days for implementation, 1 day for review)

Use the fat marker sketches to provide context and call out any additional UI states that you might need designed.

Sound good?

**Comment by henryholtgeerts** [comment]
@kevinwhoffman This sounds good to me, thanks for the update! The example issue you roughed out is help in clarifying what this process will look like.

**Comment by kevinwhoffman** [comment]
@kjohnson @henryholtgeerts Issue https://github.com/impress-org/givewp/issues/4919 is a good example of documenting our design needs so that the designers are aware of what's needed.

Today, please create a similar issue for the implementation of the Wizard design since that will be entering design over the next few days.

**Comment by henryholtgeerts** [comment]
### Call Summary
Participants: @kjohnson @henryholtgeerts 
Topic: Current progress on epic and work to be done going into next week (Henry is out most of next week)

- Onboarding Wizard app is scaffolded
- Setup page design is implemented
- Kyle is currently working to implement Stripe connect features
- Henry is currently implementing Onboarding Wizard design
- Henry committed to opening Localized Data issue for Onboarding Wizard
- Henry committed to having mock API calls in onboarding wizard by end of week
- Kyle committed to starting work on REST API endpoints this week
- Plan is for Henry's work on mock API calls to feed into Kyle's work on setting up API endpoints, Kyle will connect them next week
- Checked in and feeling good about epic timeline currently
- Talked briefly about what work will still need to be done after Henry returns

**Comment by kevinwhoffman** [comment]
## Call Summary
**Participants:** @kjohnson @henryholtgeerts @kevinwhoffman 
**Topic** Status Update & Priorities for Remainder of the Cycle

### Result
Kyle screenshared a demo of the current progress, which includes a mostly functional onboarding wizard and setup page. We identified a few key areas of focus over the next couple of days:

1. Functional form preview that reflects feature selections from the previous step
2. Complete currency configuration
3. Use of the checkmark selection indicator should be consistent across steps

We agreed that aesthetic polish and copywriting tweaks could be made next week, so that we can use the remainder of this week to nail down the major functionality.

All in all, Kyle and Henry have done a great job leading this epic and I look forward to testing the onboarding experience in the next few days.

**Comment by kjohnson** [comment]
> 3. Consistent use of the checkmark selection indicator across all relevant steps

@kevinwhoffman I addressed #<span />3 with PR [5020](https://github.com/impress-org/givewp/pull/5020), as a part of accessibility updated for the `<CardInput />` component.
