### ISSUE TITLE
Milestone block should be scaffolded

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5222]
## User Story

As a developer, I want the milestone block to be scaffolded so that I can start work on the different scopes related to Milestones.

## Visuals
🎨 [Figma Designs](https://www.figma.com/file/s5Dos5m4zXjZ8ITKZFtg3T/GiveWP-Milestones?node-id=1%3A2)

## Details
The Milestone block is used to display Milestones (progress toward a goal across different forms) on the frontend. This PR should serve to scaffold this block, putting in place the bare minimum JS and PHP needed to save some attributes and render a SSR dynamic block. Future issues will expand on this work with better scaffolding of these different areas of work (the inputs needed for the block, markup/design for the Milestone itself, etc). 

## Acceptance Criteria
-   [x] Milestone block is registered in the block editor
-   [x] Block is dynamically rendered via SSR
-   [x] Block is very loosely wireframed (to mimic fatmarker sketches)

**Comment by kjohnson** [comment]
@henryholtgeerts thoughts on bringing the JS/CSS assets into the `src/Milestone` folder/module - akin to `src/Views/Forms/Templates/Sequoia`? We could still build assets into the `assets/dist` directory.

**Comment by JasonTheAdams** [comment]
@kjohnson I would really prefer _not_ to place non-PHP assets into the `src` directory. I would like to keep that as a namespaced, back-end section of the codebase. In fact, at some point I'd like the Sequoia assets to be moved out — that one slipped by me. I don't mind if the `assets` directory mimics the `src` structure to indicate correlation.

**Comment by kjohnson** [comment]
@JasonTheAdams ok, that works for me. I was thinking in terms of Domains or Modules, but choosing to be strictly namespaced-PHP is a fair decision.

**Comment by kjohnson** [comment]
This is a test comment.

**Comment by kjohnson** [comment]
Another test comment.

**Comment by JasonTheAdams** [comment]
> I was thinking in terms of Domains or Modules, so all development was in a single place.

Yeah, I totally get where you're coming from. I've thought about it myself. What ultimately keeps me from going down that route is application architecture. Assets have to do with the front-end, Application or Presentation layers. These layers depend on the following back-end layers. As such, there isn't always a back-end domain which has a front-end component and vice versa. What does move from back-end to front-end is models, but these don't always share a domain.

Anyway, I hope that makes sense and I'm happy to chat about it more whenever you'd like. 😄
