### ISSUE TITLE
Milestone should support a title and description

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5225]
## User Story

As an admin, I want to add a custom title and description to Milestone blocks so that they better communicate my progress to users.

## Details
Currently, the Milestone block uses a hardcoded title, and does not include a description area. In the block editor, a title field and a description field should appear in the Inspector area associated with a Milestone block. As the user edits these fields, their changes should be reflected in the block preview, and when saved the changes should appear on the frontend.

## Additional Context
Currently, the Milestone block lacks high-fidelity designs. As such, the title and description should simply be added the page, in an appropriate area, without any serious effort made toward styling - that will be addressed in a future issue.

## Acceptance Criteria
-   [x] Admin can change a Milestone's title from the block inspector
-   [x] Admin can change a Milestone's description from the block inspector
-   [x] Changes are reflected in realtime in the editor, and on the frontend when saved
