### ISSUE TITLE
Milestone should support a custom goal

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5231]
## User Story

As an admin, I want Milestones to support a custom goal so that I can easily illustrate progress made across multiple donation forms.

## Details
For the sake of simplicity, a milestone goal is stored simply as an integer, which the current total is compared against to create a progress bar. In the future, as greater complexity is introduced into the Milestone block, the goal may need to be aware of what metric has been selected, or have a specific deadline tied to it. However, this issue is simply meant to introduce a `goal` attribute which can be modified and passed along to the view for display.

## Acceptance Criteria
-   [x] `goal` attribute is attached to the Milestone block
-   [x] Admin can modify a Milestone block's goal
-   [x] Changes made in the editor are reflected on the frontend
