### ISSUE TITLE
Milestone should support a specific metric (revenue, donors, donations)

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5232]
## User Story
As an admin, I want Milestones to support different metrics so that I can indicate progress toward a goal besides earnings.

## Details
Currently, Milestone only support progress measured as total earnings by a collection of forms. A Milestone should allow admin to display progress as measured by the following metrics:
- Earnings
- Number of donations
- Number of donors

## Additional Context
Selecting a metric to use should be easy within the block editor. Metric should appear as a SelectInput that defaults to Earnings.

## Acceptance Criteria
-   [ ] 'Metric' select field added to Milestone block inspector
-   [ ] Milestones default to "Earnings" metric
-   [ ] Milestones support Earnings metric
-   [ ] Milestones support Donations metric
-   [ ] Milestones support Donors metric
-   [ ] Metrics all work as expected based on selected form IDs and categories
