### ISSUE TITLE
Milestone should support sorting forms by category and tag

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5243]
## User Story

As an admin, I want to be able to filter the forms that feed into a milestone by tag and category so that if I want to quickly create a milestone for a group of forms, I don't need to add each one individually.

## Details
This feature is available in the `give_totals` shortcode, and implementation in Milestones should mirror the existing implementation.

## Acceptance Criteria
-   [x] Categories can be selected via a searchable multi-select control
-   [x] Tags can be selected via a searchable multi-select control
-   [x] Selecting categories and tags causes the Milestone to correctly filter the forms used to aggregate totals/determine progress
