### ISSUE TITLE
Admin should have admin setting to opt in and opt out from usage tracking

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5449]
## User Story

As a admin, I want to control `Usage Tracking` feature so that I can enable and disable it.

## Details
In upcoming plugin major version , We are adding usage tracking feature. We will only non-sensitive data about how GiveWP is setup and managed. We do not track or store personal data of plugin user. Admin can turn off tracking with admin setting.

## Acceptance Criteria

-   [x] Admin can see setting `Usage Tracking` from `Settings->Advanced`.
-   [x] Admin see notice nag if `Usage Tracking` disabled.
-   [x] Each admin user can disabled notice nag for one day.
