### ISSUE TITLE
[Draft] Parent theme data should add correctly to  non-sensetive tracking data

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5485]
## User Story

As a [type of user], I want [some goal] so that [some reason].

## Steps to Reproduce

1. Go to...
2. Select...
3. Scroll down to...
4. View error

## System Information

<details><summary>Details</summary>

</details>

## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by ravinderk** [comment]
This is duplicate of https://github.com/impress-org/givewp/issues/5487
