### ISSUE TITLE
[Broken functionality] Link "view all donations for this donor" in the meta card on the Donation screen shows ALL donors

### ISSUE THREAD

**Issue by tobeyadr** [impress-org/givewp#7642]
## User Story

As a developer, I want to view only the donations of a specific donor so that I can link to that screen from the Groundhogg contact screen.

## Details

When using the **View all donations for this donor** link it beings me to the donations list, but it shows **all** donations of **all** donors which is unexpected.

<img width="220" alt="image" src="https://github.com/user-attachments/assets/7cebb84d-1716-4fdc-98e6-c4cd9864bb80">

It should be noted that when the **legacy** view is enabled it works as expected, so this probably has to do with how the new table loads via AJAX.

## Expected Behavior

Only donations related to the queried donor should be shown in the table.

## Steps to Reproduce

1. Ensure the new UI is enabled
2. Go to any donation
3. Click on the **View all donations for this donor** link
4. You'll see the donations screen showing donations for all donors.

## Visuals

<img width="220" alt="image" src="https://github.com/user-attachments/assets/35050bdc-4b88-4a12-8de6-0a56a2fbb75e">
<img width="899" alt="image" src="https://github.com/user-attachments/assets/1df3ec62-4038-40dc-b5e2-e0da3b8bacc9">

## Additional Context

Works fine in the legacy UI.

## System Information

<details><summary>Details</summary>

### WordPress Environment ###

Home URL: https://groundhogg.dev
Site URL: https://groundhogg.dev
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, upgraded, give_subscription

### Server Environment ###

Hosting Provider: DBH: 127.0.0.1, SRV: groundhogg.dev
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: Apache/2.4.43 (Win32)
PHP Version: 7.4.30
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.70.0, OpenSSL/1.1.1o
SUHOSIN Installed: –
MySQL Version: 5.7.28
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 3.19.0
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Updates: All Database Migrations Completed.
Database Tables: ✔ wp_give_donors✔ wp_give_donormeta✔ wp_give_comments✔ wp_give_commentmeta✔ wp_give_sessions✔ wp_give_formmeta✔ wp_give_sequential_ordering✔ wp_give_donationmeta✔ wp_give_revenue✔ wp_give_migrations✔ wp_give_log
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔Donation Processing Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access❌Renewal Receipt Email❌Admin Renewal Receipt Email❌Subscription Cancelled Email❌Admin Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 3.18.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://groundhogg.dev/donation-confirmation/
Failure Page: https://groundhogg.dev/donation-failed/
Donation History Page: https://groundhogg.dev/donor-dashboard/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Active GiveWP Add-ons ###

Give - Funds and Designations: ✔ Licensed – by GiveWP – 2.0.1
Give - Recurring Donations: ✔ Licensed – by GiveWP – 2.11.0

### Other Active Plugins ###

Code Snippets: by Code Snippets Pro – 3.6.6.1
Groundhogg: by Groundhogg Inc. – 3.7.3
Groundhogg - Advanced Features: by Groundhogg Inc. – 3.2.6.5
Groundhogg - Birthdays: by Groundhogg Inc. – 2.2.2
Groundhogg - Companies: by Groundhogg Inc. – 3.3.0.2
Groundhogg - Conditional Funnel Logic: by Groundhogg Inc. – 3.0
Groundhogg - Content Restriction: by Groundhogg Inc. – 2.1.2.1
Groundhogg - Contracts: by Groundhogg Inc. – 2.1.3
Groundhogg - GiveWP Integration: by Groundhogg Inc. – 1.2
Groundhogg - Sales Pipeline: by Groundhogg Inc. – 3.4.2.1
Groundhogg - SMS: by Groundhogg Inc. – 2.5.2
Groundhogg - Social Proof: by Groundhogg Inc. – 2.3.0.1
Groundhogg - Zapier: by Groundhogg Inc. – 2.0.1
Query Monitor: by John Blackbourn – 3.17.0
Yoast SEO: by Team Yoast – 24.0
Yoast SEO Premium: by Team Yoast – 23.8

### Inactive Plugins ###

Advanced Custom Fields PRO: by WP Engine – 6.2.6.1
AffiliateWP: by AffiliateWP – 2.12.2
BuddyBoss Platform: by BuddyBoss – 1.9.2
Contact Form 7: by Takayuki Miyoshi – 6.0.1
Disable Emojis (GDPR friendly): by Ryan Hellyer – 1.7.6
Easy Digital Downloads: by Easy Digital Downloads – 3.3.5.2
Easy Digital Downloads (Pro): by Easy Digital Downloads – 3.3.5
Easy Digital Downloads - All Access: by Easy Digital Downloads – 1.2.7
Easy Digital Downloads - Checkout Fields Manager: by Easy Digital Downloads – 2.2.1
Easy Digital Downloads - Recurring Payments: by Easy Digital Downloads – 2.12.5
Easy Digital Downloads - Software Licensing: by Easy Digital Downloads – 3.8.14
Elementor: by Elementor.com – 3.25.10
Elementor Pro: by Elementor.com – 3.11.3
FakerPress: by Gustavo Bordoni – 0.6.6
Fluent Forms: by Contact Form - WPManageNinja LLC – 5.2.7
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.83
Formidable Forms: by Strategy11 Form Builder Team – 6.16.2
Forminator: by WPMU DEV – 1.37.1
Gravity Forms: by Gravity Forms – 2.6.4.5
Groundhogg - 3.0: by Groundhogg Inc. – 3.0
Groundhogg - Advanced Email Preferences: by Groundhogg Inc. – 1.1.1
Groundhogg - AffiliateWP: by Groundhogg Inc. – 2.0.2
Groundhogg - AWS: by Groundhogg Inc. – 2.12
Groundhogg - Backup & Restore: by Groundhogg Inc. – 1.3
Groundhogg - Booking Calendar: by Groundhogg Inc. – 3.0
Groundhogg - BuddyBoss: by Groundhogg Inc. – 1.2.2
Groundhogg - Companies: by Groundhogg Inc. – 3.1.4
Groundhogg - Contact Form 7: by Groundhogg Inc. – 2.0.1
Groundhogg -  Custom Replacements: by Groundhogg Inc. – 2.1
Groundhogg - Easy Digital Downloads Integration: by Groundhogg Inc. – 2.8.5
Groundhogg - Elastic Email: by Groundhogg Inc. – 1.2.2
Groundhogg - Elementor Integration: by Groundhogg Inc. – 2.0.8
Groundhogg - Email Countdown Timer: by Groundhogg Inc. – 3.0.6
Groundhogg - Fluent Forms: by Groundhogg Inc. – 2.0.8
Groundhogg - Forminator Integration: by Groundhogg Inc. – 2.0.1
Groundhogg - Gravity Forms Integration: by Groundhogg Inc. – 2.0.8
Groundhogg - Helper: by Groundhogg Inc. – 3.0.1
Groundhogg - Lead Scoring: by Groundhogg Inc. – 3.0.4
Groundhogg - LearnDash Integration: by Groundhogg Inc. – 2.3.1
Groundhogg - LifterLMS Integration: by Groundhogg Inc. – 2.3.4
Groundhogg - Meta Conversions API: by Groundhogg Inc. – 1.1
Groundhogg - Ninja Forms Integration: by Groundhogg Inc. – 2.0.3
Groundhogg - Postmark Integration: by Groundhogg Inc. – 1.0.7
Groundhogg - Presto Player Integration: by Groundhogg Inc. – 1.0.3
Groundhogg - Really Simple Payments: by Groundhogg Inc. – 3.0.3
Groundhogg - SendGrid Integration: by Groundhogg Inc. – 1.2.2
Groundhogg - SMTP: by Groundhogg Inc. – 2.1
Groundhogg - ThriveCart Integration: by Groundhogg Inc. – 1.0.3
Groundhogg - Tracking Traffic Filter: by Groundhogg Inc. – 1.2
Groundhogg - Twilio Integration: by Groundhogg Inc. – 2.3.8
Groundhogg - White Label: by Groundhogg Inc. – 2.0.8
Groundhogg - WooCommerce Integration: by Groundhogg Inc. – 2.7
Groundhogg - WPForms: by Groundhogg Inc. – 2.0.4
Groundhogg - ZeroBounce: by Groundhogg Inc. – 2.1
HollerBox: by Groundhogg Inc. – 2.3.8
Kadence Blocks – Gutenberg Blocks for Page Builder Features: by Kadence WP – 3.4.0
LearnDash Licensing & Management: by LearnDash – 1.3
LearnDash LMS: by LearnDash – 4.10.1
LifterLMS: by LifterLMS – 7.8.5
MailHawk: by MailHawk Inc. – 1.3.1
Newsletter Glue Pro (V2): by Newsletter Glue – 2.0.6
Ninja Forms: by Saturday Drive – 3.8.20
Ninja Forms - File Uploads: by The WP Ninjas – 3.3.14
Ninja Forms - Webhooks: by The WP Ninjas – 3.0.5
Order Simulator for WooCommerce: by 75nineteen Media LLC – 1.0.2
Presto Player: by Presto Made, Inc – 3.0.7
Presto Player Pro: by Presto Player – 2.0.4
ReviewX Pro: by ReviewX – 1.4.10
ReviewX – Multi-Criteria Rating & Reviews: by ReviewX – 2.0.3
Starter Templates by Kadence WP: by Kadence WP – 2.1.6
SVG Support: by Benbodhi – 2.5.8
Thrive Product Manager: by Thrive Themes – 1.6.1
Tipsy Theory: by Adrian Tobey – 1.0
Transients Manager: by WPBeginner – 2.0.7
User Role Editor: by Vladimir Garagulya – 4.64.3
User Switching: by John Blackbourn – 1.9.1
WooCommerce: by Automattic – 9.4.3
WooCommerce Smooth Generator: by Automattic – 1.2.0
WooCommerce Smooth Generator: by Automattic – 1.2.0
WordPress Importer: by wordpressdotorg – 0.8.3
WorkFlowy: by Adrian Tobey – 1.0
WP Activity Log: by Melapress – 5.2.2
WPCode Lite: by WPCode – 2.2.3.1
WP Console: by Edi Amin – 2.5.0
WP Crontrol: by John Blackbourn – 1.17.1
WPForms Lite: by WPForms – 1.9.2.3
WP Reset: by WebFactory Ltd – 2.04

### Theme ###

Name: Twenty Twenty-Four
Version: 1.3
Author URL: https://wordpress.org
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by tobeyadr** [comment]
It's worth noting that the equivalent functionality to view donations segmented by form via a link doesn't work either.
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/7a276b46-ac22-42ac-9ecf-06ea62f0dc44">
